package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, 7 September, 2025 12:35:43 PM IST
*/

public interface HelloOperations 
{
  String sayHello (String name);
} // interface HelloOperations
